---
title: "About"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




### Introduction and Interests: 

Writing introductions and bios can be daunting. Therefore, despite having some experience with writing in varied contexts, it is difficult escape the nervous introspection that is endemic to this process. Perhaps, it might never go away so it is always better to get on with it. 


Despite having other wide-ranging interests, my core area of focus, since high-school, has been Economics. The process which led to the cultivation of this interest has been extremely enriching and cannot be encapsulated here, given the constraints of this space. However, I will suffice it to say that the substantial contributing factor throughout this process has been my interaction with people whose guidance/advise has cultivated a lifelong curiosity about the discipline. This fascination and an innate desire to understand the process of long-term economic growth and development morphed into a decision to major in Anthropology and Development from the London School of Economics (LSE). 

 business management. Over the course of this period, I have come to the realization that the fundamental reason I have been fascinated by business management is because it is somewhat of a semi-lab generating natural experiments which advance our understanding of how economic theory evolves. To continue on this path and nurture this fascination diligently, I am currently aspiring to pursue a Master's in Business Management (MBA) from one of the topmost colleges in India. As I prepare for my entrance exams for this process, I have also decided to launch my independent writing venture focusing upon economics and business strategy. If you are interested in reading, you can find it [here](https://hiteshfulwani.substack.com/) . Consider subscribing, in case, it intrigues you!  









 










